server:
  port: 80
  address: 0.0.0.0
  tomcat:
    uri-encoding: UTF-8

# Spring 설정
spring:
  logging:
    level:
      root: INFO
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/discodeit?currentSchema=${POSTGRES_DB}
#    url: jdbc:postgresql://host.docker.internal:5432/discodeit 도커 사용시에도 내 로컬 db 연결
#    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema-psql.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: discodeit
      hibernate:
        format_sql: true
        use_sql_comments: false


management:
  endpoints:
    health:
      show-details: never
    info:
      env:
        enabled: false

  info:
    env:
      enabled: true             # 환경 변수 정보 포함
    java:
      enabled: true             # Java 정보 포함
    os:
      enabled: true             # OS 정보 포함
  prometheus:
    metrics:
      export:
        enabled: true  # 프로메테우스 메트릭 활성화
  metrics:
    tags:
      application: library-system  # 메트릭 태그 추가

file:
  upload:
    all:
      path: ./files/img

discodeit:
  storage:
    type: aws
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}


